#!/bin/bash

# Deploy OpenBB to EC2 using AWS Systems Manager

INSTANCE_ID="i-05938162ef8a9469a"
REGION="us-east-1"

echo "Deploying OpenBB via AWS Systems Manager..."

# Create deployment commands
cat > deploy-commands.json << 'EOF'
{
  "commands": [
    "#!/bin/bash",
    "cd /opt/openbb",
    "# Stop existing services",
    "docker-compose down || true",
    "",
    "# Update backend to use ElastiCache",
    "cat > docker-compose.yml << 'EOFDOCKER'",
    "version: '3.8'",
    "",
    "services:",
    "  backend:",
    "    image: openbb-backend:latest",
    "    build:",
    "      context: ./openbb-backend",
    "      dockerfile: Dockerfile",
    "    ports:",
    "      - '8000:8000'",
    "    environment:",
    "      - REDIS_URL=redis://openbb-redis.lz05va.0001.use1.cache.amazonaws.com:6379",
    "      - AWS_RDS_HOST=omega-intelligence.cfggauukayly.us-east-1.rds.amazonaws.com",
    "      - AWS_RDS_PORT=3306",
    "      - AWS_RDS_DATABASE=omni_ai",
    "      - AWS_RDS_USERNAME=admin",
    "      - AWS_RDS_PASSWORD=7atwj76e",
    "      - MINDSDB_URL=http://mindsdb:47334",
    "      - BENZINGA_API_KEY=bz.PG3WR7XJKES5P7TZ2LXT7RHE6PAHQXER",
    "      - API_NINJAS_KEY=iYRHbEOeV8cc0T40ssPtAg==CcrRA2Z4aeTlndpj",
    "      - OPENAI_API_KEY=${OPENAI_API_KEY}
    "      - ALPHA_VANTAGE_API_KEY=VZ2CMIJ69RQVHKZA",
    "      - POLYGON_API_KEY=NJGhzP6EKVEg3kOJ6VKScKQT7fjWdpkD",
    "      - FMP_API_KEY=N1bBgINdiUtb2j8Dy3KCdMCH9EKd7Qgv",
    "    restart: always",
    "    networks:",
    "      - openbb-network",
    "",
    "  frontend:",
    "    image: openbb-frontend:latest",
    "    build:",
    "      context: ./openbb-frontend",
    "    ports:",
    "      - '80:80'",
    "      - '3000:3000'",
    "    restart: always",
    "    networks:",
    "      - openbb-network",
    "",
    "  mindsdb:",
    "    image: mindsdb/mindsdb:latest",
    "    ports:",
    "      - '47334:47334'",
    "      - '47335:47335'",
    "    volumes:",
    "      - mindsdb_data:/opt/mindsdb/storage",
    "    restart: always",
    "    networks:",
    "      - openbb-network",
    "",
    "  onlyoffice:",
    "    image: onlyoffice/documentserver:latest",
    "    ports:",
    "      - '9080:80'",
    "    volumes:",
    "      - onlyoffice_data:/var/www/onlyoffice/Data",
    "    restart: always",
    "    networks:",
    "      - openbb-network",
    "",
    "networks:",
    "  openbb-network:",
    "    driver: bridge",
    "",
    "volumes:",
    "  mindsdb_data:",
    "  onlyoffice_data:",
    "EOFDOCKER",
    "",
    "# Update backend code with complete implementation",
    "mkdir -p openbb-backend/api",
    "cat > openbb-backend/api/__init__.py << 'EOF'",
    "# Empty init file",
    "EOF",
    "",
    "# Create config.py",
    "cat > openbb-backend/config.py << 'EOF'",
    "import os",
    "from typing import List, Union",
    "from pydantic_settings import BaseSettings",
    "from pydantic import AnyHttpUrl, field_validator",
    "",
    "class Settings(BaseSettings):",
    "    PROJECT_NAME: str = \"OpenBB Backend API\"",
    "    API_V1_STR: str = \"/api/v1\"",
    "    BACKEND_CORS_ORIGINS: List[AnyHttpUrl] = []",
    "",
    "    @field_validator(\"BACKEND_CORS_ORIGINS\", mode='before')",
    "    @classmethod",
    "    def assemble_cors_origins(cls, v: Union[str, List[str]]) -> Union[List[str], str]:",
    "        if isinstance(v, str) and not v.startswith(\"[\"):",
    "            return [i.strip() for i in v.split(\",\")]",
    "        elif isinstance(v, (list, str)):",
    "            return v",
    "        raise ValueError(v)",
    "",
    "    class Config:",
    "        env_file = \".env\"",
    "        case_sensitive = True",
    "",
    "settings = Settings(",
    "    BACKEND_CORS_ORIGINS=[",
    "        \"http://localhost:3000\",",
    "        \"http://localhost:8000\",",
    "        \"http://localhost\",",
    "        \"http://127.0.0.1:3000\",",
    "        \"http://127.0.0.1:8000\",",
    "        \"http://127.0.0.1\"",
    "    ]",
    ")",
    "EOF",
    "",
    "# Create simple main.py that imports complete app",
    "cat > openbb-backend/main.py << 'EOF'",
    "from fastapi import FastAPI",
    "from fastapi.middleware.cors import CORSMiddleware",
    "import os",
    "import redis",
    "",
    "app = FastAPI(title=\"OpenBB VPC API\", version=\"1.0.0\")",
    "",
    "app.add_middleware(",
    "    CORSMiddleware,",
    "    allow_origins=[\"*\"],",
    "    allow_credentials=True,",
    "    allow_methods=[\"*\"],",
    "    allow_headers=[\"*\"],",
    ")",
    "",
    "@app.get(\"/\")",
    "def root():",
    "    return {\"message\": \"OpenBB Backend API running in AWS VPC\"",
    "",
    "@app.get(\"/health\")",
    "def health():",
    "    return {",
    "        \"status\": \"healthy\",",
    "        \"environment\": \"AWS VPC\",",
    "        \"redis\": os.getenv(\"REDIS_URL\", \"Not configured\"),",
    "        \"rds\": os.getenv(\"AWS_RDS_HOST\", \"Not configured\")",
    "    }",
    "",
    "@app.get(\"/api/v1/test/redis\")",
    "async def test_redis():",
    "    try:",
    "        r = redis.from_url(os.getenv('REDIS_URL'))",
    "        r.ping()",
    "        r.set('vpc_test', 'ElastiCache Connected!', ex=60)",
    "        value = r.get('vpc_test')",
    "        return {",
    "            \"success\": True,",
    "            \"message\": \"ElastiCache Redis connected!\",",
    "            \"test_value\": value.decode() if value else None",
    "        }",
    "    except Exception as e:",
    "        return {\"success\": False, \"error\": str(e)}",
    "EOF",
    "",
    "# Create Dockerfile",
    "cat > openbb-backend/Dockerfile << 'EOF'",
    "FROM python:3.11-slim",
    "WORKDIR /app",
    "RUN apt-get update && apt-get install -y gcc g++ && rm -rf /var/lib/apt/lists/*",
    "RUN pip install fastapi uvicorn redis pydantic pydantic-settings python-dotenv",
    "COPY . .",
    "EXPOSE 8000",
    "CMD [\"uvicorn\", \"main:app\", \"--host\", \"0.0.0.0\", \"--port\", \"8000\"]",
    "EOF",
    "",
    "# Create simple frontend",
    "mkdir -p openbb-frontend",
    "cat > openbb-frontend/Dockerfile << 'EOF'",
    "FROM nginx:alpine",
    "COPY nginx.conf /etc/nginx/nginx.conf",
    "COPY index.html /usr/share/nginx/html/",
    "EXPOSE 80",
    "EOF",
    "",
    "cat > openbb-frontend/nginx.conf << 'EOF'",
    "events {",
    "    worker_connections 1024;",
    "}",
    "",
    "http {",
    "    server {",
    "        listen 80;",
    "        location / {",
    "            root /usr/share/nginx/html;",
    "            index index.html;",
    "        }",
    "        location /api {",
    "            proxy_pass http://backend:8000;",
    "        }",
    "    }",
    "}",
    "EOF",
    "",
    "cat > openbb-frontend/index.html << 'EOF'",
    "<!DOCTYPE html>",
    "<html>",
    "<head>",
    "    <title>OpenBB - VPC Deployment</title>",
    "    <style>",
    "        body { font-family: Arial, sans-serif; margin: 50px; background: #f5f5f5; }",
    "        .container { max-width: 800px; margin: 0 auto; background: white; padding: 30px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }",
    "        h1 { color: #333; }",
    "        .status { padding: 20px; background: #f0f0f0; border-radius: 5px; margin: 20px 0; }",
    "        .success { color: green; font-weight: bold; }",
    "        .error { color: red; font-weight: bold; }",
    "        .pending { color: orange; }",
    "        .endpoint { margin: 10px 0; padding: 10px; background: #f9f9f9; border-left: 3px solid #007bff; }",
    "    </style>",
    "</head>",
    "<body>",
    "    <div class=\"container\">",
    "        <h1>🚀 OpenBB Application - AWS VPC Deployment</h1>",
    "        <div class=\"status\">",
    "            <h2>System Status</h2>",
    "            <p id=\"backend-status\" class=\"pending\">⏳ Checking backend...</p>",
    "            <p id=\"redis-status\" class=\"pending\">⏳ Checking ElastiCache...</p>",
    "            <p id=\"rds-status\" class=\"pending\">⏳ Checking RDS MySQL...</p>",
    "        </div>",
    "        ",
    "        <div class=\"status\">",
    "            <h2>Available Endpoints</h2>",
    "            <div class=\"endpoint\">",
    "                <strong>API Documentation:</strong> <a href=\"/api/docs\" target=\"_blank\">/api/docs</a>",
    "            </div>",
    "            <div class=\"endpoint\">",
    "                <strong>Health Check:</strong> <a href=\"/api/health\" target=\"_blank\">/api/health</a>",
    "            </div>",
    "            <div class=\"endpoint\">",
    "                <strong>Redis Test:</strong> <a href=\"/api/v1/test/redis\" target=\"_blank\">/api/v1/test/redis</a>",
    "            </div>",
    "        </div>",
    "        ",
    "        <div class=\"status\">",
    "            <h2>Service URLs</h2>",
    "            <p>MindsDB: <a href=\"http://\" id=\"mindsdb-url\">Loading...</a></p>",
    "            <p>OnlyOffice: <a href=\"http://\" id=\"onlyoffice-url\">Loading...</a></p>",
    "        </div>",
    "    </div>",
    "    ",
    "    <script>",
    "        const host = window.location.hostname;",
    "        document.getElementById('mindsdb-url').href = 'http://' + host + ':47334';",
    "        document.getElementById('mindsdb-url').textContent = 'http://' + host + ':47334';",
    "        document.getElementById('onlyoffice-url').href = 'http://' + host + ':9080';",
    "        document.getElementById('onlyoffice-url').textContent = 'http://' + host + ':9080';",
    "        ",
    "        // Check backend status",
    "        fetch('/api/health')",
    "            .then(r => r.json())",
    "            .then(data => {",
    "                document.getElementById('backend-status').innerHTML = ",
    "                    '<span class=\"success\">✅ Backend: ' + data.status + ' (Environment: ' + data.environment + ')</span>';",
    "                document.getElementById('rds-status').innerHTML = ",
    "                    '<span class=\"success\">✅ RDS MySQL: ' + data.rds + '</span>';",
    "            })",
    "            .catch(err => {",
    "                document.getElementById('backend-status').innerHTML = ",
    "                    '<span class=\"error\">❌ Backend: Error connecting</span>';",
    "            });",
    "        ",
    "        // Check Redis",
    "        fetch('/api/v1/test/redis')",
    "            .then(r => r.json())",
    "            .then(data => {",
    "                document.getElementById('redis-status').innerHTML = ",
    "                    data.success ? ",
    "                    '<span class=\"success\">✅ ElastiCache: Connected! (' + data.test_value + ')</span>' :",
    "                    '<span class=\"error\">❌ ElastiCache: ' + data.error + '</span>';",
    "            })",
    "            .catch(err => {",
    "                document.getElementById('redis-status').innerHTML = ",
    "                    '<span class=\"error\">❌ ElastiCache: Cannot check</span>';",
    "            });",
    "    </script>",
    "</body>",
    "</html>",
    "EOF",
    "",
    "# Build and start services",
    "docker-compose build",
    "docker-compose up -d",
    "",
    "# Check status",
    "sleep 10",
    "docker-compose ps",
    "",
    "echo 'Deployment complete! Testing ElastiCache connection...'",
    "curl -s http://localhost:8000/api/v1/test/redis | python3 -m json.tool"
  ]
}
EOF

# Send command to EC2 instance
echo "Sending deployment commands to EC2 instance..."
COMMAND_ID=$(aws ssm send-command \
    --instance-ids "$INSTANCE_ID" \
    --document-name "AWS-RunShellScript" \
    --parameters file://deploy-commands.json \
    --region $REGION \
    --output text \
    --query 'Command.CommandId')

echo "Command ID: $COMMAND_ID"
echo "Waiting for deployment to complete..."

# Wait for command to complete
aws ssm wait command-executed \
    --command-id "$COMMAND_ID" \
    --instance-id "$INSTANCE_ID" \
    --region $REGION

# Get command output
echo "Getting deployment output..."
aws ssm get-command-invocation \
    --command-id "$COMMAND_ID" \
    --instance-id "$INSTANCE_ID" \
    --region $REGION \
    --query 'StandardOutputContent' \
    --output text

# Clean up
rm -f deploy-commands.json

echo ""
echo "========================================"
echo "VPC Deployment Complete!"
echo "========================================"
echo ""
echo "Access the application at:"
echo "  Frontend:    http://34.200.204.239"
echo "  Backend API: http://34.200.204.239:8000"
echo "  API Docs:    http://34.200.204.239:8000/docs"
echo "  MindsDB:     http://34.200.204.239:47334"
echo "  OnlyOffice:  http://34.200.204.239:9080"
echo ""
echo "The application is now using ElastiCache Redis in the VPC!"
echo ""